---
title: "Deployment Templates"
date: "10-01-2023"
date-modified: last-modified
---

Discover a range of sample deployment templates for the `quarto-webr` extension at our GitHub repository [here](https://github.com/coatless/quarto-webr/tree/main/examples). These templates serve as convenient starting points for various web-based projects that harness the power of the `quarto-webr` extension, enabling interactive data analysis inside of a web browser. Whether you're embarking on an individual report, creating an interactive website, or compiling a digital book, these templates simplify the process, making it effortless to kickstart your own projects.

# HTML Document Template

This template is designed for creating standalone HTML documents with interactive webR functionality. It's suitable for individual reports or interactive documents.

- **Example**: You can find an example of an HTML document template [here](https://quarto-webr.thecoatlessprofessor.com/examples/html-document/).
- **Source Code**: Access the source code for this template [here](https://github.com/coatless/quarto-webr/tree/main/examples/html-document).

# RevealJS Presentation Template

This template is designed for creating standalone RevealJS presentations with interactive webR functionality. It's suitable for creating lecture slides.

:::{.callout-important}
This template requires a [**pre-release** version of Quarto that is 1.4.502 or greater](https://quarto.org/docs/download/prerelease) that contains an updated copy of `pandoc`. For more details, please see [Issue #14](https://github.com/coatless/quarto-webr/issues/14). 
:::

- **Example**: You can find an example of a RevealJS presentation template [here](https://quarto-webr.thecoatlessprofessor.com/examples/revealjs/).
- **Source Code**: Access the source code for this template [here](https://github.com/coatless/quarto-webr/tree/main/examples/revealjs).

# Website Template

This template is meant for building interactive websites with multiple webR-powered pages. It's ideal for websites that have multiple piece of web content that requires interactive data analysis at the "top-level".

- **Example**: Explore an example of a website template [here](https://quarto-webr.thecoatlessprofessor.com/examples/website/).
- **Source Code**: Access the source code for this template [here](https://github.com/coatless/quarto-webr/tree/main/examples/website).

# Blog Template

For users who want to periodically use webR on their Quarto blog, please use the following template. 

- **Example**: Explore an example of a blog website template [here](https://quarto-webr.thecoatlessprofessor.com/examples/blog/).
- **Source Code**: Access the source code for this template [here](https://github.com/coatless/quarto-webr/tree/main/examples/blog).

# Book Template

The book template is designed for creating interactive web-based books or documentation. It allows you to compile a collection of chapters, sections, and interactive content into a cohesive digital book.

- **Example**: You can view an example of a book template [here](https://quarto-webr.thecoatlessprofessor.com/examples/book).
- **Source Code**: Access the source code for this template [here](https://github.com/coatless/quarto-webr/tree/main/examples/book).
