---
title: "Community Example Gallery"
subtitle: "Explore Real-world Use Cases and Projects Using the `quarto-webr` Extension"
date: "09-22-2023"
date-modified: last-modified
format: 
  html:
    toc: true
filters:
  - webr
---

Welcome to the Community Examples page for the `quarto-webr` extension. This section celebrates the diverse and innovative ways that members of our community are harnessing the power of the `quarto-webr` extension. These examples showcase real-world use cases, highlighting the extension's adaptability and functionality across various fields. You may also find references to examples from the [main webR project](https://webr.r-wasm.org/) here as well.

Explore the projects, applications, educational materials, and more created by fellow users. Gain inspiration from the community's contributions and discover how you can leverage the full potential of quarto-webr in your own work. Whether your interests lie in data analysis, interactive reports, or educational resources, you'll find valuable insights and ideas within the community's projects.

Do you have your own project or example that incorporates `quarto-webr`? We [invite you to contribute](https://github.com/coatless/quarto-webr/edit/main/docs/webr-community-example-gallery.qmd) to this growing collection of community-driven projects by submitting a [pull request](https://github.com/coatless/quarto-webr/edit/main/docs/webr-community-example-gallery.qmd) or [creating an issue](https://github.com/coatless/quarto-webr/issues/new?assignees=&labels=community-example&projects=&template=community-example.yml&title=%5BExample%5D%3A+). Your experiences and creativity can inspire others and promote collaboration within our community. Together, we can continue to expand the possibilities of `quarto-webr`.

# Videos

- [quarto-webr: Your first webR-powered Quarto Document (RStudio)](https://www.youtube.com/watch?v=DoRR2S5lLvk)
- [Eli E. Holmes](https://eeholmes.github.io/)' coverage of webR + Quarto on her [EEHolmes-DataScience](https://www.youtube.com/@eeholmes-datascience4849) YouTube channel
  - [Demo of webR quarto extension along with Codespaces](https://www.youtube.com/watch?v=hVLF98HP6Sw) on Mar 14, 2023 and her [test repository](https://github.com/eeholmes/test-webr)
  - [WebR + Quarto Demo: Running R right in the browser!](https://www.youtube.com/watch?v=g_2ogFn2XrY) on Mar 10, 2023 (**Note:** This uses an earlier Proof of Concept document. Not the quarto extension!)

# Teaching Workshops

- [Mine Çetinkaya-Rundel](https://mine-cr.com/)'s [Teaching Data Science Masterclass: Organizing, publishing, and sharing of course materials](https://posit-conf-2023.github.io/teach-ds-masterclass/materials/course-materials). Sept 18, 2023 @ posit::conf(2023)
  - [Ex 1.1: UN Votes](https://data-sci-101.github.io/ae/ae-01-unvotes.html), [Page Source](https://github.com/data-sci-101/data-sci-101.github.io/blob/main/ae/ae-01-unvotes.qmd)
  - Full workshop materials at [source repository](https://github.com/posit-conf-2023/teach-ds-masterclass) and deployed website example's [source repository](https://github.com/data-sci-101/data-sci-101.github.io)

# Talks

- [George Stagg](https://gws.phd)'s talk on the [Magic with WebAssembly and webR](https://gws.quarto.pub/magic-with-wasm-and-webr/#/title-slide) mentioning `quarto-webr` as an easy onboarding option. Sep 20, 2023 @ posit::conf(2023)
- [James Balamuta](http://thecoatlessprofessor.com/)'s talk on [Dynamic Interactions:Empowering Educators and Researchers with Interactive Quarto Documents Using webR](https://assets.thecoatlessprofessor.com/talks/quarto-webr-posit-conf-23-talk.pdf). Sep 19, 2023 @ posit::conf(2023)
- [George Stagg](https://gws.phd)'s talk on the [Introduction to webR](https://gws.quarto.pub/introduction-to-webr-2023/#/title-slide) mentioning `quarto-webr` as an easy onboarding option. Sep 18, 2023 @ posit::conf(2023)
- [bob Rudis](https://rud.is/)' talk on [🕸️ Into the WebR-Verse](https://github.com/hrbrmstr/2023-nyr-webr) incorporating a demo of the `quarto-webr` extension. Jul 13 @ New York R Conference 2023
  - [Video](https://www.youtube.com/watch?v=inpwcTUmBDY&list=PLlzRFZmxVl9RYNkA-lRUxloDYrd1Bhln9&index=8) and [Source code](https://github.com/hrbrmstr/2023-nyr-webr)
  - boB used a [cool trick to embed the demo](https://github.com/coatless/quarto-webr/issues/14#issuecomment-1634944155) in his revealjs slides.
- [Maria Tackett](https://maria-tackett.netlify.app/)'s talk on [Using Quarto for Making and Organizing Teaching Materials](https://mine-cetinkaya-rundel.github.io/teach-with-quarto/talks/5-teaching-materials/) during the [Teaching (with) Quarto](https://mine-cetinkaya-rundel.github.io/teach-with-quarto/) Session. Aug 7, 2023 @ JSM 2023
  - [WebR Demo](https://maria.quarto.pub/webr-demo/) on [Quarto Pub](https://quarto.pub)

# Textbooks

- [Daniel E. Weeks](https://www.sph.pitt.edu/directory/daniel-weeks)'s incorporated webR exercises into various parts of the [HuGen2071](https://danieleweeks.github.io/HuGen2071). Fall 2023.
  - [Book source](https://github.com/DanielEWeeks/HuGen2071)

# Notebooks

- [George Stagg](https://gws.phd/)'s notebook example showing [tidymodels workflow using webR](https://gws.quarto.pub/introduction-to-webr-2023/demo.html)
   - tidymodels starter article without webR [_Preprocess your data with recipes_](https://www.tidymodels.org/start/recipes/)

# Social media posts

- [Linh Nguyen](https://www.linkedin.com/in/nguyenllpsych)'s post on [LinkedIn](https://www.linkedin.com/posts/nguyenllpsych_positconf2023-activity-7111101659509899265-CTay?utm_source=share&utm_medium=member_desktop) describing how she used knowledge at posit::conf(2023) to convert existing R notes to use the `quarto-webr` extension. Sept 22, 2023
- [Joe Chelladurai](https://joechelladurai.com/) mentioning a [similiar integration on mastodon](https://mastodon.social/@joe_chelladurai@fosstodon.org/110699434655070719) for his newly developed [The School of Data](https://www.theschoolofdata.org/). Jul 11th, 2023
- [bob Rudis](https://rud.is/)' kind [praise](https://mastodon.social/@hrbrmstr/110130242863636605) of the extension. Apr 2nd, 2023

# Blog posts

- [George Stagg](https://gws.phd/)'s mention of the extension in his [webR 0.2.0 announcement](https://www.tidyverse.org/blog/2023/08/webr-0-2-0/). Aug 8th, 2023.
- [Ethan White](https://www.weecology.org/author/ethan-white/)'s use to create a [portal for Tidy Tuesday](https://tidytuesday.weecology.org/). May 2nd, 2023
- [Matt Dray](https://www.matt-dray.com/)'s post on [Playgrounds with WebR and Quarto](https://www.rostrum.blog/posts/2023-03-16-webr-quarto/). Mar 16th, 2023
  - [A Parsing Playground for R Code](https://webr-parse-test.netlify.app/) on Netlify and the [repository powering it](https://github.com/matt-dray/webr-parse-test).
- [Ethan White](https://www.weecology.org/author/ethan-white/)'s post on [Playgrounds with WebR and Quarto](https://jabberwocky.weecology.org/2023/03/13/a-brief-introduction-to-using-webr-and-quarto-for-client-side-interactive-lesson-material/). Mar 13th, 2023.
  - [A Parsing Playground for R Code](https://webr-parse-test.netlify.app/) on Netlify and the [repository powering it](https://github.com/matt-dray/webr-parse-test).

# Press

- [R Weekly podcast](https://rweekly.fireside.fm) included a reference to the Proof of Concept document/extension during [episode 115](https://rweekly.fireside.fm/115?t=763), which was dedicated to the webR 0.1.0 announcement.
   - [R weekly 115 (2023-W11)](https://rweekly.org/2023-W11.html)
