---
title: "webR-enabled code cells"
format: 
  html:
    toc: true
engine: knitr
filters:
- webr
---

## Demo

webR-enabled code cell are established by using `{webr-r}` in a Quarto HTML document.

```{webr-r}
1 + 1
```

For instance, the above `webr`-enabled code cell was created by typing into the Quarto document:

```{{webr-r}}
1 + 1
```

## Sample cases

### Fit a linear regression model

```{webr-r}
fit <- lm(mpg ~ am, data = mtcars)
summary(fit)
```

### Create a graph with base R

```{webr-r}
plot(pressure)
```


### Packages

#### Available Packages

You can view what packages are available for webR by either executing the following R code (either with WebR or just R):

```{webr-r}
available.packages(
  repos = "https://repo.r-wasm.org/",
  type = "source"
)[, c("Package", "Version")]
```

Or, by navigating to the WebR repository:

<https://github.com/r-wasm/webr-repo/blob/main/repo-packages>

#### Installing a Package

Installing a package interactively is done using `webr::install()` inside of a `{webr-r}` code cell. 

**Note:** Installing `ggplot2` may take at least 2 minutes if COEP & COOP headers are not set.

```{webr-r}
webr::install("ggplot2")
```


#### Using a Package

Once `ggplot2` is loaded, then use the package as normal.

```{webr-r}
library(ggplot2)

p <- ggplot(mpg, aes(class, hwy))
p + geom_boxplot()
```

### Define variables and re-use them in later cells

```{webr-r}
name <- "James"
age <- 42
```


```{webr-r}
message(name, " is ", age, " years old!")
```


### Escape characters in a string

```{webr-r}
seven_seas <- "Ahoy, matey!\nLet's set sail for adventure!\n"
seven_seas
```

### Anonymous function definition

```{webr-r}
add_one <- \(x) x + 1
add_one(2)
```



### Empty code cell

```{webr-r}

```


### Prior code cell

```{webr}

```


### Pre-rendered code cell

```{r}
message("Hello!")
```
